### ISSUE TITLE
openvidu-browser integration problems with ionic 3 and angular 4 (TypeError: Cannot read property 'unmask' of undefined on ws dependency)

### ISSUE THREAD

**Issue by dbarrios1907** [OpenVidu/bugtracker#1]
Hello,

I have a very simple project scenario in which I integrated ionic3 blank project with electron and openvidu-browser dependency. The problem is related to this bug tracking issue (https://github.com/websockets/ws/issues/1010).

When I serve the application it give me the following error:

D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\@ionic\app-scripts\node_modules\ws\lib\Receiver.js:306
  if (mask != null && buf != null) bufferUtil.unmask(buf, mask);
                                             ^

TypeError: Cannot read property 'unmask' of undefined
    at Receiver.unmask (D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\@ionic\app-scripts\node_modules\ws\lib\Receiver.js:306:46)
    at Receiver.finish (D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\@ionic\app-scripts\node_modules\ws\lib\Receiver.js:505:25)
    at Receiver.expectHandler (D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\@ionic\app-scripts\node_modules\ws\lib\Receiver.js:493:33)

    at Receiver.add (D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\@ionic\app-scripts\node_modules\ws\lib\Receiver.js:103:24)
    at Socket.realHandler (D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\@ionic\app-scripts\node_modules\ws\lib\WebSocket.js:825:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)

This is the dependencies in the package.json:

`"dependencies": {
  "@angular/common": "4.1.3",
  "@angular/compiler": "4.1.3",
  "@angular/compiler-cli": "4.1.3",
  "@angular/core": "4.1.3",
  "@angular/forms": "4.1.3",
  "@angular/http": "4.1.3",
  "@angular/platform-browser": "4.1.3",
  "@angular/platform-browser-dynamic": "4.1.3",
  "@ionic-native/camera": "3.12.1",
  "@ionic-native/core": "3.12.1",
  "@ionic-native/splash-screen": "3.12.1",
  "@ionic-native/status-bar": "3.12.1",
  "@ionic/storage": "2.0.1",
  "@ngrx/core": "^1.2.0",
  "@ngrx/effects": "^4.0.1",
  "@ngrx/store": "^4.0.0",
  "@ngrx/store-devtools": "^4.0.0",
  "@ngx-translate/core": "6.0.1",
  "@ngx-translate/http-loader": "0.0.3",
  "core-js": "^2.5.1",
  "hark": "^1.1.6",
  "ionic-angular": "3.6.1",
  "ionicons": "3.0.0",
  "moment": "^2.18.1",
  "openvidu-browser": "1.1.0",
  "rxjs": "5.4.0",
  "sw-toolbox": "3.6.0",
  "tassign": "^1.0.0",
  "zone.js": "0.8.12"
},
"devDependencies": {
  "@ionic/app-scripts": "2.1.4",
  "@types/electron": "^1.6.10",
  "electron": "1.7.8",
  "electron-builder": "19.31.1",
  "foreman": "^2.0.0",
  "typescript": "2.3.4"
},`

Could someone help me to resolve this integration problem ??

Thanks ahead.

**Comment by micaelgallego** [comment]
Hi dbarrios,

Are you using WS as dependency in your project? The library
openvidu-browser is not using that dependency as it is using WS support of
the browser.

When do you have this error?


El 29 sept. 2017 3:03 a. m., "dbarrios1907" <notifications@github.com>
escribió:

Hello,

I have a very simple project scenario in which I integrated ionic3 blank
project with electron and openvidu-browser dependency. The problem is
related to this bug tracking issue (websockets/ws#1010
<https://github.com/websockets/ws/issues/1010>).

When I serve the application it give me the following error:

D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\
node_modules@ionic\app-scripts\node_modules\ws\lib\Receiver.js:306
if (mask != null && buf != null) bufferUtil.unmask(buf, mask);
^

TypeError: Cannot read property 'unmask' of undefined
at Receiver.unmask (D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-
Projects\electron-openvidu\node_modules@ionic\app-
scripts\node_modules\ws\lib\Receiver.js:306:46)
at Receiver.finish (D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-
Projects\electron-openvidu\node_modules@ionic\app-
scripts\node_modules\ws\lib\Receiver.js:505:25)
at Receiver.expectHandler (D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-
Projects\electron-openvidu\node_modules@ionic\app-
scripts\node_modules\ws\lib\Receiver.js:493:33)

at Receiver.add
(D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\@ionic\app-scripts\node_modules\ws\lib\Receiver.js:103:24)
at Socket.realHandler
(D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\@ionic\app-scripts\node_modules\ws\lib\WebSocket.js:825:20)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at readableAddChunk (_stream_readable.js:176:18)
at Socket.Readable.push (_stream_readable.js:134:10)
at TCP.onread (net.js:547:20)

This is the dependencies in the package.json:

"dependencies": {
"": "4.1.3",
"": "4.1.3",
"": "4.1.3",
"": "4.1.3",
"": "4.1.3",
"": "4.1.3",
"": "4.1.3",
"": "4.1.3",
"": "3.12.1",
"": "3.12.1",
"": "3.12.1",
"": "3.12.1",
"": "2.0.1",
"": "^1.2.0",
"": "^4.0.1",
"": "^4.0.0",
"": "^4.0.0",
"": "6.0.1",
"": "0.0.3",
"core-js": "^2.5.1",
"hark": "^1.1.6",
"ionic-angular": "3.6.1",
"ionicons": "3.0.0",
"moment": "^2.18.1",
"openvidu-browser": "1.1.0",
"rxjs": "5.4.0",
"sw-toolbox": "3.6.0",
"tassign": "^1.0.0",
"zone.js": "0.8.12"
},
"devDependencies": {
"": "2.1.4",
"": "^1.6.10",
"electron": "1.7.8",
"electron-builder": "19.31.1",
"foreman": "^2.0.0",
"typescript": "2.3.4"
},

Could someone help me to resolve this integration problem ??

Thanks ahead.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenVidu/bugtracker/issues/1>, or mute the thread

**Comment by dbarrios1907** [comment]
Hi Micael,

The problem does not seem to be with the openvidu-browser library itself,
but with the integration of it "bufferutil" and "utf-8-validate"
dependencies and some of the development dependencies in my project,
specifically

"@ionic/app-scripts": "2.1.4",

and

"electron-builder": "19.31.1"

The @ionic/app-scripts is the one that includes the "ws" dependency when it
runs in "hot reloading" mode, so it compiles but when a change in the code
it's made and the reloading process executes, it exits with error:

D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\ws\lib\Receiver.js:306
  if (mask != null && buf != null) bufferUtil.unmask(buf, mask);
                                             ^

TypeError: Cannot read property 'unmask' of undefined
    at Receiver.unmask
(D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\ws\lib\Receiver.js:306:46)
    at Receiver.finish
(D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\ws\lib\Receiver.js:505:25)
    at Receiver.expectHandler
(D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\ws\lib\Receiver.js:493:33)
    at Receiver.add
(D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\ws\lib\Receiver.js:103:24)
    at Socket.realHandler
(D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\ws\lib\WebSocket.js:825:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)


On the other hand, when try to package the app with "electron-builder" a
compatibility issue shows up, once again suggesting "bufferutil" dependency
problems

> ion-electron-test@0.0.1 package
D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu
> build --win --x64

electron-builder 19.31.1
Rebuilding native production dependencies for win32:x64
Error: C:\Program Files\nodejs\node.exe exited with code 1
Output:

> bufferutil@3.0.2 install
D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\bufferutil
> prebuild-install || node-gyp rebuild


D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\bufferutil
{git}{hg}
{lamb} if not defined npm_config_node_gyp (node
"C:\Users\daniel\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js"
rebuild )  else (node "node
C:\Users\daniel\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js"
rebuild )

Error output:
prebuild-install info begin Prebuild-install version 2.2.2
prebuild-install info install installing standalone, skipping download.
module.js:471
    throw err;
    ^

Error: Cannot find module
'D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\bufferutil\node
C:\Users\daniel\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@3.0.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@3.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!
 C:\Users\daniel\AppData\Roaming\npm-cache\_logs\2017-09-29T17_01_40_045Z-debug.log

    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
    at ChildProcess.childProcess.once.code
(D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\builder-util\src\util.ts:200:14)
    at ChildProcess.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at spawn
(D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\builder-util\src\util.ts:163:3)
    at
D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\src\util\yarn.ts:172:5
From previous event:
    at rebuild
(D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\out\util\yarn.js:96:22)
    at
D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\src\util\yarn.ts:21:11
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at installOrRebuild
(D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\out\util\yarn.js:34:21)
    at
D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\src\packager.ts:338:7
    at next (native)
From previous event:
    at Packager.installAppDependencies
(D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\out\packager.js:408:11)
    at
D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\src\packager.ts:234:20
    at next (native)
From previous event:
    at Packager.doBuild
(D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\out\packager.js:344:11)
    at
D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\src\packager.ts:186:52
    at next (native)
From previous event:
    at Packager.build
(D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\out\packager.js:263:11)
    at
D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\src\builder.ts:286:40
    at next (native)
From previous event:
    at build
(D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\out\builder.js:69:21)
    at loadEnv.then
(D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.args [as handler]
(D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at Object.runCommand
(D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\yargs\lib\command.js:226:22)
    at Object.parseArgs [as _parseArgs]
(D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\yargs\yargs.js:998:24)
    at Object.get [as argv]
(D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\yargs\yargs.js:912:21)
    at Object.<anonymous>
(D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\src\cli\cli.ts:43:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! ion-electron-test@0.0.1 package: `build --win --x64`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the ion-electron-test@0.0.1 package script.
npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.

It's a rare scenario and there is no much info on the subject, I hope you
could help me to resolve the issue.

Thanks, ahead

**Comment by micaelgallego** [comment]
I see... Its a problem with the integration between ionic and electron.

We don't have experience with that platform and we can not help you. Sorry.
