### ISSUE TITLE
Demos not working

### ISSUE THREAD

**Issue by mguias** [OpenVidu/bugtracker#2]
Hi. I am not able to run the official Demos. After cklick on "Join" session/room a certificate alert apears and if i click on OK i will get a not reachable URL (https://demos.opanvidu.io:8443). 

I think it has something to do with the firewall of my firm. 

If I am @home the Demos works perfec.

Thanks

**Comment by micaelgallego** [comment]
It seems that your company is blocking port 8443. Please install demos on your own machine to avoid the issue.
